name: Tests

on: [pull_request]
  
jobs:
  my_testing:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: |
          npm -g i yarn
      
      - name: Install dependency
        run: yarn
        
      - name: lint
        run: yarn lint
        
      - name: build and test
        run: |
          yarn build
          yarn test
